import pandas as pd
a=pd.read_csv("happy19.csv",index_col='Country or region')
##print("\n\nhead section\n\n")
print(a[2])
##print("\n\ntail section\n\n")
##print(a.tail(5))
##print("\n\ncolumn section\n\n")
##print(a.columns)
##print("\n\ninfo section\n\n")
##print(a.info())
##print("\n\niloc section\n\n")
##print(a.loc[11])
#print(a.loc[["Japan","Pakistan","India"],"Overall rank"])
#print(a.shape)
